### ISSUE TITLE
Unfortunate naming

### ISSUE THREAD

**Issue by dim13** [harakeishi/whris#16]
Name `whereis` collides with system utility [whereis](https://man7.org/linux/man-pages/man1/whereis.1.html) on POSIX systems.

**Comment by harakeishi** [comment]
Rename the package.
Thank you for letting me know.

**Comment by harakeishi** [comment]
@all-contributors please add ideas

**Comment by harakeishi** [comment]
@all-contributors please add @dim13 ideas
